// NANO MANAGEMENT LAYOUTS
export const LAYOUT_EMP_TESTER_INFO_REQUEST = 'LAYOUT_EMP_TESTER_INFO_REQUEST'
export const LAYOUT_EMP_TESTER_INFO_SUCCESS = 'LAYOUT_EMP_TESTER_INFO_SUCCESS'
export const LAYOUT_EMP_TESTER_INFO_FAILURE = 'LAYOUT_EMP_TESTER_INFO_FAILURE'

export const LAYOUT_BRANCH_MARKET_INFO_REQUEST = 'LAYOUT_BRANCH_MARKET_INFO_REQUEST'
export const LAYOUT_BRANCH_MARKET_INFO_SUCCESS = 'LAYOUT_BRANCH_MARKET_INFO_SUCCESS'
export const LAYOUT_BRANCH_MARKET_INFO_FAILURE = 'LAYOUT_BRANCH_MARKET_INFO_FAILURE'

export const LAYOUT_CUSTOMER_INFO_REQUEST = 'LAYOUT_CUSTOMER_INFO_REQUEST'
export const LAYOUT_CUSTOMER_INFO_SUCCESS = 'LAYOUT_CUSTOMER_INFO_SUCCESS'
export const LAYOUT_CUSTOMER_INFO_FAILURE = 'LAYOUT_CUSTOMER_INFO_FAILURE'


export const LAYOUT_MARKETSHARE_CA_REQUEST = 'LAYOUT_MARKETSHARE_CA_REQUEST'
export const LAYOUT_MARKETSHARE_CA_SUCCESS = 'LAYOUT_MARKETSHARE_CA_SUCCESS'
export const LAYOUT_MARKETSHARE_CA_FAILURE = 'LAYOUT_MARKETSHARE_CA_FAILURE'


export const LAYOUT_MARKET_LOCKINFO_REQUEST = 'LAYOUT_MARKET_LOCKINFO_REQUEST'
export const LAYOUT_MARKET_LOCKINFO_SUCCESS = 'LAYOUT_MARKET_LOCKINFO_SUCCESS'
export const LAYOUT_MARKET_LOCKINFO_FAILURE = 'LAYOUT_MARKET_LOCKINFO_FAILURE'

export const LAYOUT_MARKET_LOCK_HANDLE_REQUEST = 'LAYOUT_MARKET_LOCK_HANDLE_REQUEST'
export const LAYOUT_MARKET_LOCK_HANDLE_SUCCESS = 'LAYOUT_MARKET_LOCK_HANDLE_SUCCESS'
export const LAYOUT_MARKET_LOCK_HANDLE_FAILURE = 'LAYOUT_MARKET_LOCK_HANDLE_FAILURE'

// NANO MANAGEMENT DASHBOARD
export const MASTER_REQUEST = 'MASTER_REQUEST'
export const MASTER_SUCCESS = 'MASTER_SUCCESS'
export const MASTER_FAILURE = 'MASTER_FAILURE'

export const REQUEST_LATEST_IMPORT = 'REQUEST_LATEST_IMPORT'
export const SUCCESS_LATEST_IMPORT = 'SUCCESS_LATEST_IMPORT'
export const FAILURE_LATEST_IMPORT = 'FAILURE_LATEST_IMPORT'

export const MASTER_REGION_REQUEST = 'MASTER_REGION_REQUEST'
export const MASTER_REGION_SUCCESS = 'MASTER_REGION_SUCCESS'
export const MASTER_REGION_FAILURE = 'MASTER_REGION_FAILURE'

export const MASTER_AREA_REQUEST = 'MASTER_AREA_REQUEST'
export const MASTER_AREA_SUCCESS = 'MASTER_AREA_SUCCESS'
export const MASTER_AREA_FAILURE = 'MASTER_AREA_FAILURE'

export const MASTER_BRANCH_REQUEST = 'MASTER_BRANCH_REQUEST'
export const MASTER_BRANCH_SUCCESS = 'MASTER_BRANCH_SUCCESS'
export const MASTER_BRANCH_FAILURE = 'MASTER_BRANCH_FAILURE'

export const MASTER_MARKET_REQUEST = 'MASTER_MARKET_REQUEST'
export const MASTER_MARKET_SUCCESS = 'MASTER_MARKET_SUCCESS'
export const MASTER_MARKET_FAILURE = 'MASTER_MARKET_FAILURE'

export const MASTER_CALIST_REQUEST = 'MASTER_CALIST_REQUEST'
export const MASTER_CALIST_SUCCESS = 'MASTER_CALIST_SUCCESS'
export const MASTER_CALIST_FAILURE = 'MASTER_CALIST_FAILURE'

export const MASTER_FILTER_OPTIONAL_REQUEST = 'MASTER_FILTER_OPTIONAL_REQUEST'
export const MASTER_FILTER_OPTIONAL_SUCCESS = 'MASTER_FILTER_OPTIONAL_SUCCESS'
export const MASTER_FILTER_OPTIONAL_FAILURE = 'MASTER_FILTER_OPTIONAL_FAILURE'

export const NANO_OK_REQUEST_FILTER = 'NANO_OK_REQUEST_FILTER'
export const NANO_OK_SUCCESS_FILTER = 'NANO_OK_SUCCESS_FILTER'
export const NANO_OK_FAILURE_FILTER = 'NANO_OK_FAILURE_FILTER'

export const GRID_MAKET_INFO_REQUEST = 'GRID_MAKET_INFO_REQUEST'
export const GRID_MAKET_INFO_SUCCESS = 'GRID_MAKET_INFO_SUCCESS'
export const GRID_MAKET_INFO_FAILURE = 'GRID_MAKET_INFO_FAILURE'

export const GRID_SUBGRID_CUSTINFO_REQUEST = 'GRID_SUBGRID_CUSTINFO_REQUEST'
export const GRID_SUBGRID_CUSTINFO_SUCCESS = 'GRID_SUBGRID_CUSTINFO_SUCCESS'
export const GRID_SUBGRID_CUSTINFO_FAILURE = 'GRID_SUBGRID_CUSTINFO_FAILURE'

export const MASTER_OVERVIEW_DASHBOARD_REQUEST = 'MASTER_OVERVIEW_DASHBOARD_REQUEST'
export const MASTER_OVERVIEW_DASHBOARD_SUCCESS = 'MASTER_OVERVIEW_DASHBOARD_SUCCESS'
export const MASTER_OVERVIEW_DASHBOARD_FAILURE = 'MASTER_OVERVIEW_DASHBOARD_FAILURE'